version = "0.2.0"

# Paramètres du générateur de listes de coupe
[liste]
v12_import_dir = "C:/V12/_WORK/IMPORT"  # Location du répertoire d'importation de Cutrite
default_bom_qty = 100                   # Quantité défaut lorsque la quantité n'est pas spécifiée.

# Paramètres de l'imprimante d'étiquettes.
[etiquette]
nom_imprimante = "Zebra (Bureau Derek)" # Trouver avec, `wmic printer get name`
multiple = 6                            # Nombre copies imprimées sera arrondi à ce multiple

# SIGM database
[database]
hostname = "192.168.0.20"
port = "5493"
name = "MFI"
username = "SIGM"

# Location d'un navigateur Web Chromium pour la génération de PDF
[chromium]
location = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"

# Location de `Sumatra PDF` pour l'impression des PDFs
[sumatrapdf]
location = "C:/Users/DSauer/scoop/apps/sumatrapdf/current/SumatraPDF.exe"