[package]
name = "coupesuite-etiquette"
version = "1.1.2"
edition = "2021"
authors = ["Derek Sauer <dsauer@megalak.ca>"]
description = "Imprimez des étiquettes de service client."
license = "MPL-2.0"

[[bin]]
name = "etiquette"
path = "src/main.rs"

[lib]
name = "etiquette"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
coupesuite-shared = { path = "../shared" }
clap = { version = "3.2", features = ["derive"] }
tokio = { version = "1.19", features = ["fs", "macros", "rt"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres"] }
tera = { version = "1.16", default-features = false }
tempfile = "3.3"
futures = "0.3"
chrono = "0.4"
