[package]
name = "coupesuite-shared"
version = "1.2.0"
edition = "2021"
authors = ["Derek Sauer <dsauer@megalak.ca>"]
description = "Fonctions communes à travers Coupésuite."
license = "MPL-2.0"

[dependencies]
anyhow = "1.0.58"
chromiumoxide = { version = "0.3.5", features = ["tokio-runtime"] }
futures = "0.3.21"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5"
tokio = {version = "1.19.2", features = ["fs", "macros", "rt"] }
sqlx = { version = "0.6.0", features = ["runtime-tokio-rustls", "postgres"] }
tera = { version = "1.16.0", default-features = false }
