[package]
name = "coupesuite-liste"
version = "0.1.0"
edition = "2021"
authors = ["Derek Sauer <dsauer@megalak.ca>"]
description = "Générez des listes de coupe pour le logiciel d'optimisation de nos scies à panneaux."
license = "MPL-2.0"

[dependencies]
coupesuite-shared = { path = "../shared" }
clap = { version = "3.2.6", features = ["derive"] }
csv = "1.1.6"
comfy-table = "6.0.0"
