[package]
name = "coupesuite-liste"
version = "0.1.0"
edition = "2021"
authors = ["Derek Sauer <dsauer@megalak.ca>"]
description = "Générez des listes de coupe pour le logiciel d'optimisation de nos scies à panneaux."
license = "MPL-2.0"

[[bin]]
name = "liste"
path = "src/main.rs"

[lib]
name = "liste"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.58"
coupesuite-shared = { path = "../shared" }
clap = { version = "3.2.6", features = ["derive"] }
csv-async = { version = "1.2.4", features = ["serde", "tokio"] }
tokio = { version = "1.19.2", features = ["full"] }
tokio-test = "0.4.2"
serde = { version = "1.0.137", features = ["derive"] }
sqlx = { version = "0.6.0", features = ["runtime-tokio-rustls", "postgres"] }
futures = "0.3.21"
